### ISSUE TITLE
Build broken in schema-serial

### ISSUE THREAD

**Issue by kovdan01** [palebedev/cosec-examples#1]
Auto-generated flatbuffers headers cannot be found from main.cpp. Tried the following ways to fix (and no result):

* Specify `PRE_BUILD` option in `add_custom_command` (this should not have any impact but why not)
* Call `ninja` command with `-j1` option (thought that parallel build might be the reason)
* Use `add_custom_target` instead of `add_custom_command` and then call `add_dependencies` (I know that `add_custom_command` is preferable because it is called only when needed, just tried to investigate)
* Include this header with `""` instead of `<>`
* Move `ntc_target(schema-serial)` before `flat_buffers_autogen(schema-serial)` (thought that `ntc_target` call might overwrite some needed options)

The most interesting thing is that this header **IS** actually generated and placed inside `include` subdirectory in the build directory.

One more thing: I managed to build the project successfully several times, but I can't describe how to reproduce it. It was just like "changed something in the corresponding `CMakeLists.txt`, and it built successfully". However, after deleting the build directory the "clear" build fails.

Can it be a bug in CMake? Can't find a way to make the code work correctly (and it actually should work correctly, but does not). I use: CMake 3.19.2, ninja 1.10.2, gcc 10.2.0.

```
[33/89] Building CXX object schema-serial/CMakeFiles/schema-serial.dir/src/main.cpp.o
FAILED: schema-serial/CMakeFiles/schema-serial.dir/src/main.cpp.o
/usr/sbin/c++ -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_ATOMIC_DYN_LINK -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_LOG_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -I../utils/include -isystem utils/include -g -pedantic-errors -fno-math-errno -fno-signed-zeros -fno-trapping-math -Wall -Wextra -Wcast-align -Wconversion -Wctor-dtor-privacy -Wdeprecated -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra-semi -Wimplicit-fallthrough -Wlogical-op -Wmissing-declarations -Wno-assume -Wno-missing-field-initializers -Wnull-dereference -Wold-style-cast -Wpragmas -Wredundant-decls -Wundef -Wzero-as-null-pointer-constant -ftemplate-backtrace-limit=0 -fdiagnostics-show-template-tree -gsplit-dwarf -std=c++2a -MD -MT schema-serial/CMakeFiles/schema-serial.dir/src/main.cpp.o -MF schema-serial/CMakeFiles/schema-serial.dir/src/main.cpp.o.d -o schema-serial/CMakeFiles/schema-serial.dir/src/main.cpp.o -c ../schema-serial/src/main.cpp
../schema-serial/src/main.cpp:1:10: fatal error: widget_generated.h: No such file or directory
    1 | #include <widget_generated.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by kovdan01** [comment]
@palebedev Do you face this compile error on your local machine? I get it both on Arch Linux virtual machine (VMWare Workstation Pro 16.1.0) and Arch Linux under WSL 2 (Windows 20H2)

**Comment by palebedev** [comment]
Does 82cee28535f853cf4df60be08d7c9932bc76a404 help?

**Comment by kovdan01** [comment]
Yes, build with GCC 10.2.0 under Arch Linux works (in both Debug in Release modes). Thank you!
